server {
    listen 80;
    server_name _;
    charset utf-8;

    location /yuxiaofeng/ {
        alias /root/myfacebook/myfacebook/public/;
        index index.html;
    }
    location /yuxiaofeng {
        return 301 /yuxiaofeng/;
    }
}
